name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get more storage space
        uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Enable Magic Nix cache action
        uses: DeterminateSystems/magic-nix-cache-action@main

      # - uses: cachix/cachix-action@v16
      #   with:
      #     name: <CACHE-NAME>
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run tests
        run: >
          nix flake check --accept-flake-config
