name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get more storage space
        uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Enable Magic Nix cache action
        uses: DeterminateSystems/magic-nix-cache-action@main

      # - uses: cachix/cachix-action@v16
      #   with:
      #     name: <CACHE-NAME>
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run tests
        run: nix flake check --accept-flake-config

      - name: Test deployment configuration
        run: |
          nix build .#terraformConfigurations.all -o config.tf.json
          nix develop .#deployment --command tofu init
          nix develop .#deployment --command tofu validate
