name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get more storage space
        uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Enable Magic Nix cache action
        uses: DeterminateSystems/magic-nix-cache-action@main

      # - uses: cachix/cachix-action@v16
      #   with:
      #     name: <CACHE-NAME>
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run framework checks
        run: nix flake check --accept-flake-config

      - name: Initialize project from template
        run: |
          mkdir -p ${{ runner.temp }}/test-project
          cd ${{ runner.temp }}/test-project

          nix flake init -t ${{ github.workspace }}
          sed -i 's|nixos-framework.url = "github:imincik/nixos-framework";|nixos-framework.url = "path:${{ github.workspace }}";|' flake.nix

      - name: Run template tests
        run: nix flake check --accept-flake-config
        working-directory: ${{ runner.temp }}/test-project

      - name: Test deployment configuration
        run: |
          nix build .#terraformConfigurations.all -o config.tf.json
          nix develop .#deployment --command tofu init
          nix develop .#deployment --command tofu validate
        working-directory: ${{ runner.temp }}/test-project
